import { TrainingBlock, TrainingSession } from "@/types/training";

// 목업 훈련 블록들
const mockBlocks1: TrainingBlock[] = [
    {
        id: "block-1",
        type: "warmup",
        title: "동적 스트레칭",
        duration: 10,
        description: "전신 동적 스트레칭으로 몸 풀기",
        intensity: "low",
        coachingPoints: ["관절 가동 범위 확보", "심박수 점진적 상승"],
        equipment: [],
    },
    {
        id: "block-2",
        type: "main",
        title: "론도 (4v2)",
        duration: 15,
        description: "4명이 공을 돌리고 2명이 빼앗기",
        intensity: "medium",
        coachingPoints: ["빠른 판단", "몸 열기", "첫 터치 방향"],
        equipment: ["콘", "조끼"],
    },
    {
        id: "block-3",
        type: "main",
        title: "패스 앤 무브",
        duration: 20,
        description: "패스 후 즉시 이동하는 훈련",
        intensity: "high",
        coachingPoints: ["패스 정확도", "오프더볼 움직임", "타이밍"],
        equipment: ["콘", "마커"],
    },
    {
        id: "block-4",
        type: "game",
        title: "미니 게임 (5v5)",
        duration: 20,
        description: "좁은 공간에서 미니 게임",
        intensity: "high",
        coachingPoints: ["훈련 내용 적용", "의사소통"],
        equipment: ["미니골대", "조끼"],
    },
    {
        id: "block-5",
        type: "cooldown",
        title: "정적 스트레칭",
        duration: 10,
        description: "주요 근육군 스트레칭",
        intensity: "low",
        coachingPoints: ["호흡 조절", "충분한 시간 유지"],
        equipment: [],
    },
];

const mockBlocks2: TrainingBlock[] = [
    {
        id: "block-6",
        type: "warmup",
        title: "볼 터치 워밍업",
        duration: 10,
        description: "볼과 함께하는 가벼운 워밍업",
        intensity: "low",
        equipment: ["볼"],
    },
    {
        id: "block-7",
        type: "main",
        title: "슈팅 연습",
        duration: 25,
        description: "다양한 각도에서 슈팅 연습",
        intensity: "high",
        coachingPoints: ["차는 발 위치", "팔로우스루", "골키퍼 위치 확인"],
        equipment: ["볼", "골대"],
    },
    {
        id: "block-8",
        type: "game",
        title: "하프코트 게임",
        duration: 25,
        description: "슈팅 상황 만들기에 집중",
        intensity: "high",
        equipment: ["조끼", "골대"],
    },
    {
        id: "block-9",
        type: "cooldown",
        title: "조깅 및 스트레칭",
        duration: 10,
        description: "가벼운 조깅 후 스트레칭",
        intensity: "low",
        equipment: [],
    },
];

// 목업 훈련 세션들
export const mockSessions: TrainingSession[] = [
    {
        id: "session-1",
        userId: "user-1",
        title: "패스 집중 훈련",
        createdAt: new Date("2025-01-18T10:00:00"),
        updatedAt: new Date("2025-01-18T10:00:00"),
        conditions: {
            playerCount: 12,
            totalDuration: 75,
            fieldType: "half",
            teamLevel: "amateur",
            goals: ["passing", "possession"],
            hasGoalkeeper: false,
            hasInjuredPlayers: false,
        },
        blocks: mockBlocks1,
        isAiGenerated: true,
        aiExplanation:
            "12명의 동호회 수준 선수들을 위한 패스와 점유율 향상 훈련입니다. 론도와 패스 앤 무브를 통해 빠른 판단력과 정확한 패스를 연습하고, 미니 게임에서 실전 적용해봅니다.",
        isFavorite: true,
        tags: ["패스", "점유율", "동호회"],
    },
    {
        id: "session-2",
        userId: "user-1",
        title: "슈팅 강화 훈련",
        createdAt: new Date("2025-01-17T14:00:00"),
        updatedAt: new Date("2025-01-17T15:30:00"),
        conditions: {
            playerCount: 10,
            totalDuration: 70,
            fieldType: "half",
            teamLevel: "amateur",
            goals: ["shooting"],
            hasGoalkeeper: true,
            hasInjuredPlayers: false,
        },
        blocks: mockBlocks2,
        isAiGenerated: true,
        aiExplanation:
            "슈팅 능력 향상에 초점을 맞춘 훈련입니다. 다양한 각도와 상황에서의 슈팅 연습 후, 게임을 통해 실전 슈팅 감각을 키웁니다.",
        isFavorite: false,
        tags: ["슈팅"],
    },
    {
        id: "session-3",
        userId: "user-1",
        title: "수비 전술 훈련",
        createdAt: new Date("2025-01-15T09:00:00"),
        updatedAt: new Date("2025-01-15T09:00:00"),
        conditions: {
            playerCount: 14,
            totalDuration: 90,
            fieldType: "full",
            teamLevel: "amateur",
            goals: ["defense", "pressing"],
            hasGoalkeeper: true,
            hasInjuredPlayers: true,
        },
        blocks: mockBlocks1,
        isAiGenerated: false,
        isFavorite: false,
        tags: ["수비", "압박"],
    },
];

// 빈 조건 기본값
export const defaultConditions = {
    playerCount: 10,
    totalDuration: 60,
    fieldType: "half" as const,
    teamLevel: "amateur" as const,
    goals: [] as string[],
    hasGoalkeeper: false,
    hasInjuredPlayers: false,
};
